#
# cloud_rc_file: Point this to the overcloudrc file you're going to use
#
cloud_rc_file: /home/stack/overcloudrc
#
# ports: These are the ports that will be created on your VyOS appliance.
#        NOTE:  In the default configuration:
#
#               eth0 - should be your Provider Network and have any IP address
#               you choose on that network.
#
#               eth1 - should connect to your private tenant network.  The 
#               IP address you give to eth1 should be the configured 
#               DEFAULT GATEWAY of that private tenant network.
#
#   nic:        Name of the interface on the VyOS appliance
#   os_network: Name of the network in Openstack that will be connected to that NIC
#               ** NETWORK MUST ALREADY EXISTS **
#   address:    The IP address assigned to this NIC. Ensure this is outside the DHCP
#               range of the network
#   prefix:     Subnet prefix of the Openstack network
#
ports:
  - { nic: 'eth0', os_network: 'vlan118', address: '10.9.64.250', prefix: '26' }
  - { nic: 'eth1', os_network: 'private', address: '192.168.0.1', prefix: '24' }
#
# routes: Static routes to be added to the VyOS appliance. 
#         NOTE: In the default configuration, the next_hop is the IP address of 
#               the DEFAULT GATEWAY of your Provider Network.
#
#
routes:
  - { route: '0.0.0.0/0', next_hop: '10.9.64.193' }
#
# ntp_servers: List of NTP servers to configure on the VyOS appliance
#
ntp_servers:
  - 0.fedora.pool.ntp.org
  - 1.fedora.pool.ntp.org
  - 2.fedora.pool.ntp.org
  - 3.fedora.pool.ntp.org
#
# name_servers: List of DNS servers to configure on the VyOS appliance
#
name_servers:
  - 10.11.5.19
  - 10.5.30.160
#
# nat_rules: Name Address Translation rules to be configured on the VyOS appliance
#            NOTE: Currently this playbook only supports:
#                  source NAT - masquerading 
#                  destination NAT - port forwarding
#
nat_rules:
  - { index: '1', type: 'source', outbound_interface: 'eth0', source_address: '192.168.0.1/24', translation_address: 'masquerade' }
#
# services: These are the services to configure on the VyOS appliance and their associated settings
#           NOTE: Currently this playbook only supports configuring the following VyOS Services:
#                 dns_forwarding
#                 ssh
#
services:
  - { name: 'dns_forwarding', name_server: '10.11.5.19', listen_port: 'eth1' }
  - { name: 'ssh', listen_address: '0.0.0.0', listen_port: '2222' }
#
# users: The user to configure on the VyOS appliance
#        NOTE: This is the user which cloud-init will inject the ssh-key to
#
users:
  - { name: 'vyos', password: 'Redhat01' }
#
# vyos_create_instance: Setting this to True will launch an instance of the VyOS appliance on Openstack
#                       and pass a configured user_data file to the instance to configure the appliance
#
vyos_create_instance: True
#
# vm_create_instance: Setting this to True will launch an instance of the Cirros on the private tenant network on Openstack
#
vm_create_instance: True
